[platformio]
default_envs = coordinator_c6

; --- GLOBAL CONFIGURATION ---
[env]
framework = arduino
monitor_speed = 115200
; Use the pioarduino fork for all ESP32 variants to ensure C6/RISC-V support
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip


[common_libs]
lib_deps_common =
    bblanchon/ArduinoJson @ ^7.0.4
    knolleary/PubSubClient @ ^2.8
    mathieucarbou/ESP Async WebServer
	mathieucarbou/AsyncTCP

lib_deps_esp8266 = 
    bblanchon/ArduinoJson @ ^7.0.4
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9

lib_deps_ignore = 
	Async TCP

; --- 1. COORDINATOR (ESP32-C6, ESP32-S3) ---
[env:coordinator_c6]
board = esp32-c6-devkitc-1
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D HAS_RGB_LED
build_src_filter = +<coordinator.cpp> +<web/web.cpp> -<sensor_node.example.cpp> -<gateway.cpp> -<relay.cpp>
lib_deps = 
    ${common_libs.lib_deps_common}
    adafruit/Adafruit NeoPixel @ ^1.12.3
lib_ignore = 
    ${common_libs.lib_deps_ignore}

;Lilygo T8 S3 has 16MB flash and PSRAM, 
[env:coordinator_t8_s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions/t8_s3.csv
build_flags =
    -D BOARD_HAS_PSRAM
build_src_filter = +<coordinator.cpp> +<web/web.cpp> -<sensor_node.example.cpp> -<gateway.cpp> -<relay.cpp>
lib_deps =
    ${common_libs.lib_deps_common}
lib_ignore =
    ${common_libs.lib_deps_ignore}

; [env:coordinator_s3]
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
; board = esp32-s3-devkitc-1
; build_flags = 
;     -D ARDUINO_USB_CDC_ON_BOOT=1
;     -D ARDUINO_USB_MODE=1
; build_src_filter = +<coordinator.cpp> +<web/web.cpp> -<sensor_node.example.cpp> -<gateway.cpp> -<relay.cpp>
; lib_deps = 
;     ${common_libs.lib_deps_common}
; lib_ignore = 
;     ${common_libs.lib_deps_ignore}


; --- 2. SENSOR NODE (Generic ESP32) ---
[env:sensor_node]
board = esp32dev 
build_src_filter = +<sensor_node.example.cpp> -<coordinator.cpp> -<gateway.cpp> -<relay.cpp>

; --- 3. DISPLAY GATEWAY (ESP8266) ---
[env:gateway_esp8266]
platform = espressif8266
board = nodemcuv2
build_src_filter = +<gateway.cpp> -<coordinator.cpp> -<sensor_node.example.cpp> -<relay.cpp>
lib_deps = 
    ${common_libs.lib_deps_esp8266}
lib_ignore = 
    ${common_libs.lib_deps_ignore}

