; --- ESP32-C6 (CDC + RGB LED) ---
; --- Standard coordinator Now -> MQTT ---
[env:coordinator_c6]
board = esp32-c6-devkitc-1
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D HAS_RGB_LED
    -D UM_DEBUG_MODE=0     ; <-- This instantly strips all serial prints out of the compiled firmware!
build_src_filter = 
    -<*> 
    +<coordinators/coordinator.cpp> 
lib_deps = 
    ${common_libs.lib_deps_common}
    adafruit/Adafruit NeoPixel @ ^1.12.3
lib_ignore = 
    ${common_libs.lib_deps_ignore}

; --- LILYGO T8 S3 (16MB + PSRAM) ---
[env:coordinator_t8_s3]
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions/t8_s3_16mb.csv
build_flags =
    -D BOARD_HAS_PSRAM
build_src_filter = -<*> +<coordinators/coordinator.cpp> +<coordinators/web.cpp>
lib_deps =
    ${common_libs.lib_deps_common}
lib_ignore =
    ${common_libs.lib_deps_ignore}

; --- LILYGO ETH ELITE (Ethernet + PSRAM) ---
[env:coordinator_eth_elite]
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions/ethelite_16MB.csv
build_flags =
    -D BOARD_HAS_PSRAM
    -D LILYGO_T_ETH_ELITE
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D MESH_HOSTNAME=\"universalmesh\"
    -D OTA_PASSWORD=\"mesh1234\"
build_src_filter = -<*> +<coordinators/coordinator.cpp> +<coordinators/web.cpp> +<coordinators/eth.cpp>
lib_deps =
    ${common_libs.lib_deps_common}
lib_ignore =
    ${common_libs.lib_deps_ignore}

; --- LILYGO ETH ELITE (OTA Mode) ---
[env:coordinator_eth_elite_ota]
extends = env:coordinator_eth_elite
upload_port = 192.168.2.208
upload_protocol = espota
upload_flags = --auth=mesh1234

; --- STANDARD ESP32-S3 (4MB) ---
[env:coordinator_s3]
board = esp32-s3-devkitc-1
build_src_filter = -<*> +<coordinators/coordinator.cpp> +<coordinators/web.cpp>
lib_deps = 
    ${common_libs.lib_deps_common}
lib_ignore = 
    ${common_libs.lib_deps_ignore}